package main

import (
	"../"
	"fmt"
	//"io/ioutil"
	//"path/filepath"
)

func main() {
	/*
		files, _ := ioutil.ReadDir("../fonts")
		for _, f := range files {
			name := f.Name()[0 : len(f.Name())-len(filepath.Ext(f.Name()))]
			fmt.Println(`fmt.Println(termcolors.BannerPrintLineS("=", 40))`)
			fmt.Println(`fmt.Println("` + name + `")`)
			fmt.Println(`termcolors.PrintNewFigure("TEST","` + name + `",true)`)
		}
	*/
	output()
}

func output() {
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("3-d")
	termcolors.PrintNewFigure("TEST", "3-d", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("3x5")
	termcolors.PrintNewFigure("TEST", "3x5", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("5lineoblique")
	termcolors.PrintNewFigure("TEST", "5lineoblique", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("acrobatic")
	termcolors.PrintNewFigure("TEST", "acrobatic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("alligator")
	termcolors.PrintNewFigure("TEST", "alligator", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("alligator2")
	termcolors.PrintNewFigure("TEST", "alligator2", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("alphabet")
	termcolors.PrintNewFigure("TEST", "alphabet", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("avatar")
	termcolors.PrintNewFigure("TEST", "avatar", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("banner")
	termcolors.PrintNewFigure("TEST", "banner", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("banner3-D")
	termcolors.PrintNewFigure("TEST", "banner3-D", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("banner3")
	termcolors.PrintNewFigure("TEST", "banner3", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("banner4")
	termcolors.PrintNewFigure("TEST", "banner4", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("barbwire")
	termcolors.PrintNewFigure("TEST", "barbwire", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("basic")
	termcolors.PrintNewFigure("TEST", "basic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("bell")
	termcolors.PrintNewFigure("TEST", "bell", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("big")
	termcolors.PrintNewFigure("TEST", "big", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("bigchief")
	termcolors.PrintNewFigure("TEST", "bigchief", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("binary")
	termcolors.PrintNewFigure("TEST", "binary", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("block")
	termcolors.PrintNewFigure("TEST", "block", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("bubble")
	termcolors.PrintNewFigure("TEST", "bubble", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("bulbhead")
	termcolors.PrintNewFigure("TEST", "bulbhead", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("calgphy2")
	termcolors.PrintNewFigure("TEST", "calgphy2", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("caligraphy")
	termcolors.PrintNewFigure("TEST", "caligraphy", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("catwalk")
	termcolors.PrintNewFigure("TEST", "catwalk", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("chunky")
	termcolors.PrintNewFigure("TEST", "chunky", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("coinstak")
	termcolors.PrintNewFigure("TEST", "coinstak", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("colossal")
	termcolors.PrintNewFigure("TEST", "colossal", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("computer")
	termcolors.PrintNewFigure("TEST", "computer", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("contessa")
	termcolors.PrintNewFigure("TEST", "contessa", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("contrast")
	termcolors.PrintNewFigure("TEST", "contrast", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("cosmic")
	termcolors.PrintNewFigure("TEST", "cosmic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("cosmike")
	termcolors.PrintNewFigure("TEST", "cosmike", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("cricket")
	termcolors.PrintNewFigure("TEST", "cricket", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("cursive")
	termcolors.PrintNewFigure("TEST", "cursive", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("cyberlarge")
	termcolors.PrintNewFigure("TEST", "cyberlarge", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("cybermedium")
	termcolors.PrintNewFigure("TEST", "cybermedium", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("cybersmall")
	termcolors.PrintNewFigure("TEST", "cybersmall", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("diamond")
	termcolors.PrintNewFigure("TEST", "diamond", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("digital")
	termcolors.PrintNewFigure("TEST", "digital", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("doh")
	termcolors.PrintNewFigure("TEST", "doh", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("doom")
	termcolors.PrintNewFigure("TEST", "doom", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("dotmatrix")
	termcolors.PrintNewFigure("TEST", "dotmatrix", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("drpepper")
	termcolors.PrintNewFigure("TEST", "drpepper", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("eftichess")
	termcolors.PrintNewFigure("TEST", "eftichess", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("eftifont")
	termcolors.PrintNewFigure("TEST", "eftifont", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("eftipiti")
	termcolors.PrintNewFigure("TEST", "eftipiti", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("eftirobot")
	termcolors.PrintNewFigure("TEST", "eftirobot", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("eftitalic")
	termcolors.PrintNewFigure("TEST", "eftitalic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("eftiwall")
	termcolors.PrintNewFigure("TEST", "eftiwall", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("eftiwater")
	termcolors.PrintNewFigure("TEST", "eftiwater", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("epic")
	termcolors.PrintNewFigure("TEST", "epic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("fender")
	termcolors.PrintNewFigure("TEST", "fender", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("fourtops")
	termcolors.PrintNewFigure("TEST", "fourtops", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("fuzzy")
	termcolors.PrintNewFigure("TEST", "fuzzy", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("goofy")
	termcolors.PrintNewFigure("TEST", "goofy", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("gothic")
	termcolors.PrintNewFigure("TEST", "gothic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("graffiti")
	termcolors.PrintNewFigure("TEST", "graffiti", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("hollywood")
	termcolors.PrintNewFigure("TEST", "hollywood", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("invita")
	termcolors.PrintNewFigure("TEST", "invita", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("isometric1")
	termcolors.PrintNewFigure("TEST", "isometric1", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("isometric2")
	termcolors.PrintNewFigure("TEST", "isometric2", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("isometric3")
	termcolors.PrintNewFigure("TEST", "isometric3", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("isometric4")
	termcolors.PrintNewFigure("TEST", "isometric4", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("italic")
	termcolors.PrintNewFigure("TEST", "italic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("ivrit")
	termcolors.PrintNewFigure("TEST", "ivrit", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("jazmine")
	termcolors.PrintNewFigure("TEST", "jazmine", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("jerusalem")
	termcolors.PrintNewFigure("TEST", "jerusalem", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("katakana")
	termcolors.PrintNewFigure("TEST", "katakana", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("kban")
	termcolors.PrintNewFigure("TEST", "kban", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("larry3d")
	termcolors.PrintNewFigure("TEST", "larry3d", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("lcd")
	termcolors.PrintNewFigure("TEST", "lcd", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("lean")
	termcolors.PrintNewFigure("TEST", "lean", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("letters")
	termcolors.PrintNewFigure("TEST", "letters", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("linux")
	termcolors.PrintNewFigure("TEST", "linux", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("lockergnome")
	termcolors.PrintNewFigure("TEST", "lockergnome", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("madrid")
	termcolors.PrintNewFigure("TEST", "madrid", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("marquee")
	termcolors.PrintNewFigure("TEST", "marquee", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("maxfour")
	termcolors.PrintNewFigure("TEST", "maxfour", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("mike")
	termcolors.PrintNewFigure("TEST", "mike", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("mini")
	termcolors.PrintNewFigure("TEST", "mini", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("mirror")
	termcolors.PrintNewFigure("TEST", "mirror", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("mnemonic")
	termcolors.PrintNewFigure("TEST", "mnemonic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("morse")
	termcolors.PrintNewFigure("TEST", "morse", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("moscow")
	termcolors.PrintNewFigure("TEST", "moscow", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("nancyj-fancy")
	termcolors.PrintNewFigure("TEST", "nancyj-fancy", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("nancyj-underlined")
	termcolors.PrintNewFigure("TEST", "nancyj-underlined", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("nancyj")
	termcolors.PrintNewFigure("TEST", "nancyj", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("nipples")
	termcolors.PrintNewFigure("TEST", "nipples", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("ntgreek")
	termcolors.PrintNewFigure("TEST", "ntgreek", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("o8")
	termcolors.PrintNewFigure("TEST", "o8", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("ogre")
	termcolors.PrintNewFigure("TEST", "ogre", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("pawp")
	termcolors.PrintNewFigure("TEST", "pawp", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("peaks")
	termcolors.PrintNewFigure("TEST", "peaks", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("pebbles")
	termcolors.PrintNewFigure("TEST", "pebbles", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("pepper")
	termcolors.PrintNewFigure("TEST", "pepper", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("poison")
	termcolors.PrintNewFigure("TEST", "poison", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("puffy")
	termcolors.PrintNewFigure("TEST", "puffy", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("pyramid")
	termcolors.PrintNewFigure("TEST", "pyramid", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("rectangles")
	termcolors.PrintNewFigure("TEST", "rectangles", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("relief")
	termcolors.PrintNewFigure("TEST", "relief", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("relief2")
	termcolors.PrintNewFigure("TEST", "relief2", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("rev")
	termcolors.PrintNewFigure("TEST", "rev", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("roman")
	termcolors.PrintNewFigure("TEST", "roman", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("rot13")
	termcolors.PrintNewFigure("TEST", "rot13", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("rounded")
	termcolors.PrintNewFigure("TEST", "rounded", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("rowancap")
	termcolors.PrintNewFigure("TEST", "rowancap", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("rozzo")
	termcolors.PrintNewFigure("TEST", "rozzo", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("runic")
	termcolors.PrintNewFigure("TEST", "runic", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("runyc")
	termcolors.PrintNewFigure("TEST", "runyc", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("sblood")
	termcolors.PrintNewFigure("TEST", "sblood", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("script")
	termcolors.PrintNewFigure("TEST", "script", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("serifcap")
	termcolors.PrintNewFigure("TEST", "serifcap", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("shadow")
	termcolors.PrintNewFigure("TEST", "shadow", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("short")
	termcolors.PrintNewFigure("TEST", "short", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("slant")
	termcolors.PrintNewFigure("TEST", "slant", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("slide")
	termcolors.PrintNewFigure("TEST", "slide", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("slscript")
	termcolors.PrintNewFigure("TEST", "slscript", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("small")
	termcolors.PrintNewFigure("TEST", "small", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("smisome1")
	termcolors.PrintNewFigure("TEST", "smisome1", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("smkeyboard")
	termcolors.PrintNewFigure("TEST", "smkeyboard", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("smscript")
	termcolors.PrintNewFigure("TEST", "smscript", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("smshadow")
	termcolors.PrintNewFigure("TEST", "smshadow", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("smslant")
	termcolors.PrintNewFigure("TEST", "smslant", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("smtengwar")
	termcolors.PrintNewFigure("TEST", "smtengwar", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("speed")
	termcolors.PrintNewFigure("TEST", "speed", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("stampatello")
	termcolors.PrintNewFigure("TEST", "stampatello", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("standard")
	termcolors.PrintNewFigure("TEST", "standard", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("starwars")
	termcolors.PrintNewFigure("TEST", "starwars", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("stellar")
	termcolors.PrintNewFigure("TEST", "stellar", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("stop")
	termcolors.PrintNewFigure("TEST", "stop", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("straight")
	termcolors.PrintNewFigure("TEST", "straight", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("tanja")
	termcolors.PrintNewFigure("TEST", "tanja", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("tengwar")
	termcolors.PrintNewFigure("TEST", "tengwar", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("term")
	termcolors.PrintNewFigure("TEST", "term", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("thick")
	termcolors.PrintNewFigure("TEST", "thick", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("thin")
	termcolors.PrintNewFigure("TEST", "thin", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("threepoint")
	termcolors.PrintNewFigure("TEST", "threepoint", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("ticks")
	termcolors.PrintNewFigure("TEST", "ticks", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("ticksslant")
	termcolors.PrintNewFigure("TEST", "ticksslant", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("tinker-toy")
	termcolors.PrintNewFigure("TEST", "tinker-toy", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("tombstone")
	termcolors.PrintNewFigure("TEST", "tombstone", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("trek")
	termcolors.PrintNewFigure("TEST", "trek", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("tsalagi")
	termcolors.PrintNewFigure("TEST", "tsalagi", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("twopoint")
	termcolors.PrintNewFigure("TEST", "twopoint", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("univers")
	termcolors.PrintNewFigure("TEST", "univers", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("usaflag")
	termcolors.PrintNewFigure("TEST", "usaflag", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("wavy")
	termcolors.PrintNewFigure("TEST", "wavy", true)
	fmt.Println(termcolors.BannerPrintLineS("=", 40))
	fmt.Println("weird")
	termcolors.PrintNewFigure("TEST", "weird", true)
}
